### ISSUE TITLE
compiled C++ code for the model object is (sometimes) invalid

### ISSUE THREAD

**Issue by Felipe-Osorio** [stan-dev/rstanarm#36] opened 2015-11-09 22:56 UTC
I'm working with some simulated data and started by running a few simple models. I'm assuming the generic Gaussian GLM is pre-compiled in rstanarm -- I'd installed 2.8.1 directly. This could be an idiosyncrasy of working off clone VMs, but I got the following error:
```
> rstan1 <- stan_glmer(qty ~ price + (1 + price | prod_key)
+                      , data = df
+                      , chains = 4
+                      , iter = 1000
+                      , prior = normal(0, 2)
+                      , prior_intercept = normal(100, 40)
+                      )
starting worker pid=24456 on localhost:11133 at 14:04:11.818
starting worker pid=24465 on localhost:11133 at 14:04:12.164
starting worker pid=24474 on localhost:11133 at 14:04:12.491
starting worker pid=24483 on localhost:11133 at 14:04:12.796
Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: the compiled object from C++ code for this model is invalid, possible reasons:
  - compiled with save_dso=FALSE;
  - compiled on a different platform;
  - not existed (created from reading csv files).
> stan_trace(rstan1)
Error in if (object$algorithm == "optimizing") stop("Plots not yet available for optimization (algorithm='optimizing')",  : 
  argument is of length zero
> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.0 (Maipo)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rstan_2.8.1     ggplot2_1.0.1   shinystan_2.0.1 shiny_0.12.2    rstanarm_2.8.1  Rcpp_0.12.1     arm_1.8-6       lme4_1.1-10     Matrix_1.2-1    MASS_7.3-40    
[11] lazyeval_0.1.10 dplyr_0.4.1    

loaded via a namespace (and not attached):
 [1] lattice_0.20-31     zoo_1.7-12          gtools_3.5.0        assertthat_0.1      digest_0.6.8        mime_0.4            R6_2.1.1            plyr_1.8.1         
 [9] stats4_3.2.1        coda_0.18-1         httr_0.6.1          minqa_1.2.4         nloptr_1.0.4        DT_0.1              shinythemes_1.0.1   proto_0.3-10       
[17] devtools_1.9.1.9000 splines_3.2.1       shinyjs_0.2.3       RcppEigen_0.3.2.5.1 stringr_0.6.2       htmlwidgets_0.5     loo_0.1.3.9000      RCurl_1.95-4.5     
[25] munsell_0.4.2       httpuv_1.3.3        base64enc_0.1-3     htmltools_0.2.6     gridExtra_2.0.0     threejs_0.2.1       codetools_0.2-11    matrixStats_0.15.0 
[33] withr_1.0.0         bitops_1.0-6        BH_1.58.0-1         grid_3.2.1          nlme_3.1-120        xtable_1.8-0        gtable_0.1.2        DBI_0.3.1          
[41] magrittr_1.5        StanHeaders_2.8.0   scales_0.2.4        reshape2_1.4.1      dygraphs_0.5        xts_0.9-7           tools_3.2.1         markdown_0.7.7     
[49] abind_1.4-3         parallel_3.2.1      inline_0.3.14       colorspace_1.2-4    memoise_0.2.1       knitr_1.11   
```

The traceback() output was unusual -- mostly comprised of a long list of numbers, presumably sampling args. It's interesting that if I try this model on a single chain (eschewing the parallel calls), it suddenly works. Because this error only sometimes happens, it's been tricky to pinpoint and diagnose. I don't recall it happening prior to 2.8.0, but this may just be one of the drawbacks of working with the bleeding edge versions...

**Comment by bgoodri** [comment] 2015-11-09 23:44
We have seen things like this from Windows but never RedHat. Are you sure that the versions of packages being loaded up by the child nodes are the same as in the parent node?

**Comment by Felipe-Osorio** [comment] 2015-11-10 15:57
Good point -- I'm not sure, but it's clearly worth considering.

**Comment by jgabry** [comment] 2016-01-06 16:57
@bgoodri Do you think we can close this now with rstan 2.9 release?

**Comment by bgoodri** [comment] 2016-01-06 17:05
I'm not sure it was ever reproducible.

**Comment by jgabry** [comment] 2016-01-06 17:06
Ok, I'm going to close this and if people get the error again we'll reopen.

**Closed by jgabry** 2016-01-06 17:06 UTC
Labels: minor bug

**Comment by davidmanheim** [comment] 2017-05-10 01:23
I'm getting the error in windows - but I suspect it's a version conflict as I just upgraded stan, and it had some trouble installing.

**Comment by stemangiola** [comment] 2018-06-10 01:56
With a fresh ubuntu + R + Rstudio + rstan I get this error

```
> fit_horseshoe_sigmoid_C2_2= rstan:::stan(
+   model_code = works_, 
+   data= data_sigma,
+   iter=   500, warmup = 250,
+   chains = 3,
+   cores = 3,
+   save_dso = FALSE
+ )
recompiling to avoid crashing R session
starting worker pid=2848 on localhost:11000 at 11:51:59.121
starting worker pid=2857 on localhost:11000 at 11:51:59.310
starting worker pid=2866 on localhost:11000 at 11:51:59.502
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: the compiled object from C++ code for this model is invalid, possible reasons:
  - compiled with save_dso=FALSE;
  - compiled on a different platform;
  - does not exist (created from reading csv files).
```
While I it works if I set save_dso=TRUE

Session info

`R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] MASS_7.3-49           bindrcpp_0.2.2        tidybayes_0.12.1.9000
 [4] rstan_2.17.3          StanHeaders_2.17.2    forcats_0.3.0        
 [7] stringr_1.3.1         dplyr_0.7.5           purrr_0.2.5          
[10] readr_1.1.1           tidyr_0.8.1           tibble_1.4.2         
[13] ggplot2_2.2.1         tidyverse_1.2.1       foreach_1.4.4        

loaded via a namespace (and not attached):
 [1] ggstance_0.3              tidyselect_0.2.4         
 [3] reshape2_1.4.3            haven_1.1.1              
 [5] lattice_0.20-35           colorspace_1.3-2         
 [7] stats4_3.4.4              yaml_2.1.19              
 [9] rlang_0.2.1               pillar_1.2.3             
[11] foreign_0.8-69            glue_1.2.0               
[13] modelr_0.1.2              readxl_1.1.0             
[15] bindr_0.1.1               plyr_1.8.4               
[17] munsell_0.4.3             gtable_0.2.0             
[19] cellranger_1.1.0          rvest_0.3.2              
[21] coda_0.19-1               LaplacesDemon_16.1.0     
[23] codetools_0.2-15          psych_1.8.4              
[25] labeling_0.3              inline_0.3.15            
[27] parallel_3.4.4            broom_0.4.4              
[29] Rcpp_0.12.17              arrayhelpers_1.0-20160527
[31] scales_0.5.0              jsonlite_1.5             
[33] gridExtra_2.3             mnormt_1.5-5             
[35] digest_0.6.15             svUnit_0.7-12            
[37] hms_0.4.2                 stringi_1.2.2            
[39] grid_3.4.4                cli_1.0.0                
[41] tools_3.4.4               magrittr_1.5             
[43] lazyeval_0.2.1            crayon_1.3.4             
[45] pkgconfig_2.0.1           xml2_1.2.0               
[47] ggridges_0.5.0            lubridate_1.7.4          
[49] assertthat_0.2.0          httr_1.3.1               
[51] rstudioapi_0.7            iterators_1.0.9          
[53] R6_2.2.2                  nlme_3.1-131             
[55] compiler_3.4.4           `

**Comment by bgoodri** [comment] 2018-06-10 02:03
This should not have been put under the **rstanarm** repo because it does not involve **rstanarm**. Also, it tells you one possible reason for this (known) behavior is `compiled with save_dso=FALSE`, which is why it works when you set `save_dso = TRUE`.
