### ISSUE TITLE
update in posterior_vs_prior does not specify warmup, leads to warmup > iter

### ISSUE THREAD

**Issue by stijnmasschelein** [stan-dev/rstanarm#383] opened 2019-08-30 07:50 UTC
#### Summary:
The `update` call in the `posterior_vs_prior` function does not specify the `warmup` argument. So the argument is set by whatever is in the original stan_glm call. 

#### Description:
If the user specifies `warmup = some_number` in the stan_glm call, some_number is used to generate the prior distribution in `posterior_vs_prior`.
If `warmup = 2000`, there are no prior samples which leads to the problem [in this thread](https://discourse.mc-stan.org/t/issue-using-posterior-vs-prior-with-poisson-or-neg-binomial-models/10599/4). 
If `warmup > 2000`, the update step borks because iter < warmup. 
If `1000 > warmup > 2000`, there will be less prior samples than I think was intended with the function. Especially `1950 > warmup > 2000` although unlikely might be problematic because it could lead to relatively noisy prior distributions without alerting the user to a problem.

#### Reproducible Steps:
```{r}
require(rstanarm)
x = rnorm(100)
y = rpois(100, exp(x))
d = data.frame(x = x, y = y)

set.seed(230383)
# This works 
glm_def <- stan_glm(y ~ x, data = d)
posterior_vs_prior(glm_def)
# This works
glm_4000 <- stan_glm(y ~ x, data = d, iter = 4000)
posterior_vs_prior(glm_4000)
# This does not work
glm_4000_2000 <- stan_glm(y ~ x, data = d, iter = 4000, warmup = 2000)
posterior_vs_prior(glm_4000_2000)
upd_4000_2000 <- update(glm_4000_2000, prior_PD = TRUE, 
                        refresh = -1, iter = 2000, chains = 2)
# This works
glm_6000 <- stan_glm(y ~ x, data = d, iter = 6000)
posterior_vs_prior(glm_6000)
upd_6000 <- update(glm_6000, prior_PD = TRUE, 
                   refresh = -1, iter = 2000, chains = 2)
# This throws another exciting error
glm_6000_3000 <- stan_glm(y ~ x, data = d, iter = 6000, warmup = 3000)
posterior_vs_prior(glm_6000_3000)
upd_6000_3000 <- update(glm_6000_3000, prior_PD = TRUE, 
                 refresh = -1, iter = 2000, chains = 2)
upd_6000_3000_fix <- update(glm_6000_3000, prior_PD = TRUE, 
                     refresh = -1, iter = 2000, warmup = 1000, chains = 2)
```

#### RStanARM Version:
2.18.2

#### R Version:
3.5.3

#### Operating System:
OSX 10.13.6

**Comment by mcol** [comment] 2019-09-05 12:06
I can reproduce your errors. I think there are two separate issues.

- Inside `posterior_vs_prior()`  there is a call to `update()`  with an hardcoded `iter=2000`: by removing that, it will use whatever was used in `stan_glm()`, and so there is no inconsistency between iter/warmup. This fixes these two calls:
   - `posterior_vs_prior(glm_4000_2000)`
   - `posterior_vs_prior(glm_6000_3000)`
- The error on calling `update()` is unrelated, as it happens independently of calling `posterior_vs_prior()` and of setting the `prior_PD` option:
  - `upd_4000_2000 <- update(glm_4000_2000, iter = 2000)`: this effectively doesn't collect any samples after warmup, and it's possibly a bug in **rstan** (in `rstan:::config_argss()` there's a check for `warmup > iter` which should be `warmup >= iter`
  - `upd_6000_3000 <- update(glm_6000_3000, iter = 2000)`: this fails correctly as the `rstan` check above triggers

**Comment by stijnmasschelein** [comment] 2019-09-06 05:23
Thanks for following up on this. I did not think anything was wrong with update, sorry for the confusion. That was my quick and dirty way of testing whether the problem was in the update step of `posterior_vs_prior()`.

**Comment by jgabry** [comment] 2019-09-16 18:12
@stijnmasschelein Thanks for reporting and for the reproducible example. Closing since #384 was merged (thanks @mcol) and the other issue is in rstan #693.

**Closed by jgabry** 2019-09-16 18:12 UTC
