### ISSUE TITLE
Compilation Error on OS X (when installing from GitHub)

### ISSUE THREAD

**Issue by dw006** [stan-dev/rstanarm#61] opened 2016-01-20 12:14 UTC
Hi all,

using
```devtools::install_github("stan-dev/rstanarm", args = "--preclean", build_vignettes = TRUE)```
I try to install rstanarm on my OS X (10.11.3) with R 3.2.3 and Rstudio 0.99.850. 

Compilation stops with:

clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
make: *** [rstanarm.so] Error 1
ERROR: compilation failed for package ‘rstanarm’

Actually, I do not find these files in any other directory. So, I guess I need to install libfont and libreadline.
What is the recommend way to do so?

Thank you in advance!

**Comment by jgabry** [comment] 2016-01-20 17:06
Thanks for reporting the error. I haven't seen this particular error
before. @bgoodri have you seen this?

Does installing the CRAN version also fail or only if you install the
development version from github using devtools?

**Comment by dw006** [comment] 2016-01-20 17:24
Thank you for your response.

The error only comes up with the devtools installation. Seems to be an
issue somewhere in the compilation.

But no worries, as the cran version works and is perfect for my purposes, I
stay with that one. I was trying out the devtools installation more out of
curiosity.

Thank you for a great project!



2016-01-20 18:06 GMT+01:00 Jonah Gabry <notifications@github.com>:

> Thanks for reporting the error. I haven't seen this particular error
> before. @bgoodri have you seen this?
>
> Does installing the CRAN version also fail or only if you install the
> development version from github using devtools?
>

**Comment by jgabry** [comment] 2016-01-20 18:01
Ok thanks. We'll get this sorted out so that the development version is
also installable, but I'm glad the CRAN version is working. We'll also
get an update up on CRAN over the next week or so which will have all of
the fixes and additions currently on GitHub.

**Comment by bgoodri** [comment] 2016-01-22 19:07
What happens if you try to install it without `build_vignettes = TRUE`?

**Comment by jgabry** [comment] 2016-01-22 20:33
I think building the vignettes might be the problem. On mac for me it installs fine from GitHub when not building the vignettes but has trouble when `build_vignettes = TRUE`. That said, the problem I'm seeing is not the same clang error reported by @dw006, but rather 

    Writing NAMESPACE
    Error: Can not find template reference-stan-manual
    In addition: Warning message:
    In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
    there is no package called ‘rstan (>= 2.9.0)’
    Execution halted

however then it seems to continue trying to install, does a bunch of other stuff, and then eventually reports that

    No man pages found in package  ‘rstanarm’ 

Again, this only happens when `build_vignettes = TRUE`

**Comment by jgabry** [comment] 2016-01-22 20:40
@bgoodri Does this happen on your Linux system too?

**Comment by bgoodri** [comment] 2016-01-22 20:47
No, but then again I have libreadline, etc.

**Comment by jgabry** [comment] 2016-01-22 20:57
So installing with `build_vignettes = TRUE` works fine for you? I don't get that error about libreadline though, just those strange errors in my previous message.

**Comment by bgoodri** [comment] 2016-01-22 20:58
Yes

**Comment by jgabry** [comment] 2016-01-22 20:59
Ok, weird. I have no idea why we're seeing these errors on Mac all of a
sudden.

**Comment by dw006** [comment] 2016-01-26 08:31
Interestingly, without ```build_vignettes = TRUE``` I receive the same error:

    clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
    clang: error: no such file or directory: '/usr/local/lib/libreadline.a'

**Comment by jgabry** [comment] 2016-01-27 20:59
Hmm, that's strange. Unfortunately I'm not sure why you're getting that error and I can't replicate it (so it's hard to sort out). So for now I'm not sure what the issue is but my hunch is that it's not something unique to rstanarm, it's just that trying to install rstanarm might be the only thing you're doing that triggers this error (I might be wrong about that, but that's my hunch). At least the CRAN version installs for you, and we'll be getting an update of rstanarm up on CRAN soon, so I assume you should then be able to install the most recent version.

**Comment by bgoodri** [comment] 2016-01-27 21:08
Does
```
install.packages("rstanarm", type = "source")
```
work for the OP?

**Comment by davharris** [comment] 2016-04-15 23:48
For what it's worth, I can successfully use `devtools::install_github("stan-dev/rstanarm", args = "--preclean", build_vignettes = TRUE)` on my mac (OS version 10.11.4, R version 3.2.4). This could mean that the problem has been fixed, or that I just happened to have the dependency on my machine already.

**Comment by jgabry** [comment] 2016-07-21 22:41
I think this hasn't been a problem for a while now so I'm going to close this issue. But definitely reopen if the problem persists.

**Closed by jgabry** 2016-07-21 22:41 UTC
Labels: installation
