### ISSUE TITLE
certain kinds of random effects don't work with posterior_predict

### ISSUE THREAD

**Issue by aammd** [stan-dev/rstanarm#187] opened 2017-05-10 14:37 UTC
#### Summary:

For models with certain types of random effects, it seems that `posterior_predict` (more specifically, `ranef`) doesn't work.

#### Description:

When fitting a model with random effects -- something like ` + (1|group) + (0 + x2 | group)`, it seems that `posterior_predict` does not behave as expected. However, it does work fine with other random effects (e.g. just one of the terms above).

#### Reproducible Steps:

Here is a reprex, based on the example in `?posterior_predict`:

```r
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
library(rstanarm)
#> Loading required package: Rcpp
#> rstanarm (Version 2.14.1, packaged: )
#> - Do not expect the default priors to remain the same in future rstanarm versions.
#> Thus, R scripts should specify priors explicitly, even if they are just the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#> options(mc.cores = parallel::detectCores())
xx <- data.frame(counts, outcome, treatment)
fit3 <- stan_glmer(counts ~ 0 + outcome + treatment + (1|treatment) + (0+outcome|treatment), family = poisson(link="log"),
                 prior = normal(0, 1), prior_intercept = normal(0, 5), data = xx, chains = 2)
#> 
#> SAMPLING FOR MODEL 'count' NOW (CHAIN 1).
#> 
#> Chain 1, Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 1, Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 1, Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 1, Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 1, Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 1, Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 1, Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 1, Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 1, Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 1, Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 1, Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 1, Iteration: 2000 / 2000 [100%]  (Sampling)
#>  Elapsed Time: 3.68657 seconds (Warm-up)
#>                3.36301 seconds (Sampling)
#>                7.04958 seconds (Total)
#> 
#> 
#> SAMPLING FOR MODEL 'count' NOW (CHAIN 2).
#> 
#> Chain 2, Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 2, Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 2, Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 2, Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 2, Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 2, Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 2, Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 2, Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 2, Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 2, Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 2, Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 2, Iteration: 2000 / 2000 [100%]  (Sampling)
#>  Elapsed Time: 3.93845 seconds (Warm-up)
#>                3.52763 seconds (Sampling)
#>                7.46608 seconds (Total)
#> Warning: There were 2 divergent transitions after warmup. Increasing adapt_delta above 0.95 may help. See
#> http://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup
#> Warning: Examine the pairs() plot to diagnose sampling problems
nd <- data.frame(treatment = factor(rep(1,3)), outcome = factor(1:3))
ytilde <- posterior_predict(fit3, nd, draws = 500)
#> Error in data.frame(do.call(cbind, ml[i]), row.names = levs[[i]], check.names = FALSE): row names supplied are of the wrong length
```

#### RStanARM Version:

`'2.14.1'`

#### R Version:

`'3.3.2'`

#### Operating System:

OS X 10.11.6

**Comment by jgabry** [comment] 2017-05-11 22:43
Thanks for the bug report. There's a newer version of rstanarm than the one
you're running, but I'm not sure if this is fixed. We'll look into it.

@bgoodri was this fixed with 2.15.3? If not we should sort this out asap.

**Comment by jgabry** [comment] 2017-05-15 14:47
Ok I can confirm that this error persists in the latest release 2.15.3. @bgoodri any idea how to tweak your code to resolve this? As @aammd alluded to the issue seems to be with `ranef` and it messes up `posterior_predict` when the `.pp_data_mer_z` helper function calls `ranef` internally.

**Comment by tuxedopong** [comment] 2017-05-23 21:41
+1. I've seen this in a few different ways.

e.g. `posterior_predict` also fails under the following scenario (borrowing from @aammd's reprex environment above):

```
...
fit4 <- stan_glmer(counts ~ 0 + outcome + treatment + (1+outcome||treatment), family = poisson(link="log"),
                   prior = normal(0, 1), prior_intercept = normal(0, 5), data = xx, chains = 2, iter=900)
nd <- data.frame(treatment = factor(rep(1,3)), outcome = factor(1:3))
ytilde <- posterior_predict(fit4, nd, draws = 500)
```

**Closed** 2017-06-26 15:04 UTC
Labels: bug
