### ISSUE TITLE
new_CppObject_xp error

### ISSUE THREAD

**Issue by rvhulst** [stan-dev/rstanarm#206] opened 2017-07-17 13:09 UTC
#### Summary:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer

#### Description:
non fatal error when doing the command:
Mbudworm2 <- stan_glm(formula = cbind(dead, 20 - dead) ~ ldose * sex,
family = binomial, data = budworm, prior = student_t(df = 7),
prior_intercept = student_t(df = 7))
Trying to estimate the parameters of a logistic regression 

#### RStanARM Version:
version 2.15.3 of rstanarm

#### R Version:
verson 3.4.1 of R

#### Operating System:
Ubuntu linux 16.04.2 LTS

**Comment by bgoodri** [comment] 2017-07-17 14:41
Duplicate of #202 and will be fixed by 2.16.x

**Closed by bgoodri** 2017-07-17 14:41 UTC
